### ISSUE TITLE
Implement Poet Upload & Persistence

### ISSUE THREAD

**Issue by connorwalsh** [connorwalsh/new-yorken-poesry-magazine#14]
# Overview
when creating poets, a user should be able to upload an executable file and an optional parameters file

# Requirements
* uploaded files should be stored on the filesystem

# TODO
- [x] return http responses
- [x] write validate functions for users and poets
- [ ] ~unit tests (for everything we did)~ (delegated to issue #16)
- [ ] ~refactor the `User.Create()` id argument weirdness~ (delegated to issues #17)
- [ ] ~standardize the http data format (form vs. raw data)~ (delegated to issue #18)
- [x] implement the session token expiration goroutine
