### ISSUE TITLE
Dockerize Application (Prod+Dev)

### ISSUE THREAD

**Issue by connorwalsh** [connorwalsh/new-yorken-poesry-magazine#7]
# Overview
* containerize application for prod
* containerize application for dev

# TODO
- [x] prod Dockerfile at project root
  - [x] build golang server
  - [x] build static js bundle
  - [x] copy only server binary and js bundle to image
  - [x] specify entrypoint cmd
- [x] prod docker-compose.yml at project root
  - [x] run prod docker container to depend on db container
  - [x] configure & run db container (Postgres)
- [x] dev Dockerfile for server (in server directory)
  - [x] copy entire local codebase into container
  - [x] entrypoint cmd to compile and run server
  - [x] setup fs watcher to recompile and re-run server when src files change
- [x] dev Dockerfile for client (in client dir)
  - [x] copy entire local codebase into container
  - [x] entrypoint cmd to start node dev server
  - [ ] redirect requests to server **TODO**
- [x] dev docker-compose.yml
  - [x] run dev server docker container (depends on db)
  - [x] run dev client docker container
  - [x] run db container

- [x] clean up docker-compose service namespaces
- [x] make sure server can connect to db
- [ ] make sure in dev env, client requests are redirected to server **TODO**
- [ ] use Docker secrets **TODO**

**Comment by connorwalsh** [comment]
There are three **TODO**s still left, but i will address these once we start working on developing the frontend
